package com.alan.generator.junit.testcase.service.impl;

import com.alan.generator.junit.testcase.base.BaseControllerTest;
import com.alan.generator.junit.testcase.service.impl.AccountServiceImpl;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.web.servlet.MockMvc;

/**
* Generated by Java Code Generator on 23/12/2022
*/
@WebMvcTest(controllers=AccountServiceImpl.class)
public class AccountServiceImplTestCase extends BaseControllerTest {

	private MockMvc mockMvc;

	@Test
	public void given_when_then() {
		// GIVEN
		// TODO
		
		// WHEN
		// TODO
		
		// THEN
		// TODO
	}

}
