package com.alan.generator.junit.testcase.controller.impl;

import com.alan.generator.junit.testcase.base.BaseControllerTest;
import com.alan.generator.junit.testcase.service.impl.AccountServiceImpl;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.*;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;

/**
* Generated by Java Code Generator on 23/12/2022
*/
@WebMvcTest(controllers=AccountServiceImpl.class)
public class AccountServiceImplTestCase extends BaseControllerTest {

	@Test
	public void given_when_then() {
		// GIVEN
		// TODO
		
		// WHEN
		// TODO
		
		// THEN
		// TODO
	}

}
