package com.alan.generator.junit.testcase.controller;

import com.alan.generator.junit.testcase.base.BaseControllerTest;
import com.alan.generator.junit.testcase.controller.AccountController;
import com.alan.generator.junit.testcase.service.AccountService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.web.servlet.MockMvc;

/**
 * Generated by Java Code Generator on 23/12/2022
 */
@WebMvcTest(controllers = AccountController.class)
public class AccountControllerTestCase extends BaseControllerTest {

    private MockMvc mockMvc;
    private AccountService accountService;

    @Test
    public void given_when_then() {
	// GIVEN
	// TODO

	// WHEN
	// TODO

	// THEN
	// TODO
    }

}
