package com.alan.generator.junit.testcase;

import com.alan.generator.junit.testcase.UserTestCase;
import com.alan.generator.junit.testcase.target.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/12/2022
*/
@Component
public class UserTest {

	private UserTestCase userTestCase;

	@Autowired
	public UserTest(UserTestCase userTestCase) {
		this.userTestCase = userTestCase;
	}

}
