package com.alan.generator.junit.testcase;

import com.alan.generator.junit.testcase.target.User;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
* Generated by Java Code Generator on 23/12/2022
*/
public class UserTestCase {

	@BeforeEach
	public void setUp() {
		// TODO
	}

	@AfterEach
	public void tearDown() {
		// TODO
	}

	@Test
	public void given_when_then() {
		// GIVEN
		// TODO
		
		// WHEN
		// TODO
		
		// THEN
		// TODO
	}

}
