package com.fet.telemedicine.backend.infrastructure.repository.jpa;

import com.fet.telemedicine.backend.infrastructure.repository.jpa.po.Account;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Java Code Generator on 28/12/2022
*/
@Repository
public interface AccountRepository extends JpaRepository<Account, Integer>, JpaSpecificationExecutor<Account> {

}
